runtime: java11
env: standard
env_variables:
  SPRING_PROFILES_ACTIVE: "app-engine"
  JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Sao_Paulo"
instance_class: B2
handlers:
- url: .*
  script: auto
manual_scaling:
  instances: 1
network: {}